#!/usr/bin/env python3
"""Genera biblioteca de lectura/fichado con historial de revisiones."""
from __future__ import annotations
import csv, json
from pathlib import Path

DATA=Path('data/master_records.csv'); DOCS=Path('docs'); DOCS.mkdir(exist_ok=True)
REPORTS=[
 {'date':'2026-07-30','base':2975,'new':200,'sources':'OpenAlex: 172 · CONICET Digital: 27 · ambos: 1'},
 {'date':'2026-07-31','base':2979,'new':4,'sources':'OpenAlex: 3 · CONICET Digital: 1'},
 {'date':'2026-08-01','base':2986,'new':7,'sources':'OpenAlex: 7'},
 {'date':'2026-08-04','base':3000,'new':14,'sources':'OpenAlex: 14'},
 {'date':'2026-08-07','base':3005,'new':5,'sources':'OpenAlex: 5'},
 {'date':'2026-08-10','base':3026,'new':21,'sources':'OpenAlex: 20 · CONICET Digital: 1'},
 {'date':'2026-08-13','base':3031,'new':5,'sources':'OpenAlex: 5'},
]
def s(v): return str(v or '').strip()
def records():
    if not DATA.exists(): return []
    csv.field_size_limit(20_000_000)
    with DATA.open(encoding='utf-8-sig',newline='') as f: rows=list(csv.DictReader(f))
    out=[]
    for r in rows:
        title=s(r.get('title'))
        if not title: continue
        doi=s(r.get('doi')); url=s(r.get('url')) or (f'https://doi.org/{doi}' if doi else '')
        out.append({'record_id':s(r.get('record_id')) or doi or title,'title':title,'authors':s(r.get('authors')),'year':s(r.get('publication_year')),'date':s(r.get('publication_date')),'source':s(r.get('source')),'origin':s(r.get('origin')),'abstract':s(r.get('abstract')),'keywords':s(r.get('keywords')),'doi':doi,'url':url,'pdf_url':s(r.get('pdf_url')),'first_seen_date':s(r.get('first_seen_date'))})
    out.sort(key=lambda x:(x['first_seen_date'],x['year'],x['title']),reverse=True); return out

HTML=r'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Biblioteca | SCRAPEADORACADEMICO</title><style>
:root{--bg:#0d1117;--p:#161b22;--p2:#111820;--line:#30363d;--tx:#e6edf3;--mut:#8b949e;--blue:#58a6ff;--green:#3fb950}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--tx);font:14px Segoe UI,Arial,sans-serif}a{color:var(--blue);text-decoration:none}button,input,select,textarea{font:inherit;color:var(--tx);background:#0d1117;border:1px solid var(--line);border-radius:7px;padding:8px 10px}button{cursor:pointer}.primary{background:#1f6feb;border-color:#1f6feb}.green{background:#238636;border-color:#238636}header{padding:12px 16px;border-bottom:1px solid var(--line);background:#0b1018;position:sticky;top:0;z-index:20}.top{display:flex;justify-content:space-between;align-items:center;gap:12px}.brand{font-size:1.2rem;font-weight:800}.sub,.meta{color:var(--mut);font-size:.8rem}.tools{display:grid;grid-template-columns:1fr 150px 150px;gap:8px;margin-top:10px}.library{display:grid;grid-template-columns:minmax(520px,1fr) 340px;gap:10px;height:calc(100vh - 112px);padding:10px}.pane{background:var(--p);border:1px solid var(--line);border-radius:9px;overflow:hidden}.ph{padding:10px 12px;border-bottom:1px solid var(--line);background:var(--p2);display:flex;justify-content:space-between}.list{height:calc(100% - 42px);overflow:auto}.art,.report{padding:10px 12px;border-bottom:1px solid #242b35;cursor:pointer}.art:hover,.report:hover{background:#1c2530}.title{font-weight:650;line-height:1.35}.pill{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:2px 7px;margin:4px 4px 0 0;font-size:.72rem}.report-date{font-size:1rem;font-weight:800;color:var(--blue)}
.overlay{position:fixed;inset:0;background:var(--bg);z-index:100;display:none}.overlay.open{display:flex;flex-direction:column}.ovh{height:58px;display:flex;align-items:center;justify-content:space-between;padding:10px 16px;border-bottom:1px solid var(--line);background:#0b1018}.ovbody{flex:1;overflow:auto;padding:20px;max-width:1200px;width:100%;margin:auto}.report-paper{padding:12px 0;border-bottom:1px solid var(--line)}
.reader{position:fixed;inset:0;background:var(--bg);z-index:120;display:none;grid-template-columns:1fr 1fr}.reader.open{display:grid}.reading{min-width:0;border-right:1px solid var(--line);display:flex;flex-direction:column}.rh{height:58px;padding:9px 12px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:8px}.viewer{flex:1;min-height:0}.viewer iframe{width:100%;height:100%;border:0;background:white}.fallback{height:100%;overflow:auto;padding:24px;line-height:1.65}.sheet{min-width:0;overflow:auto;padding:14px 18px}.sheet h2{font-size:1rem;margin:0 0 12px}.form{margin-bottom:10px}.form label{display:block;color:var(--mut);font-size:.72rem;margin-bottom:4px}.form input,.form textarea,.form select{width:100%}.form textarea{min-height:82px;resize:vertical}.g2{display:grid;grid-template-columns:1fr 1fr;gap:8px}.autosave{position:sticky;bottom:0;background:var(--p);padding:9px;border:1px solid var(--line);border-radius:8px;color:var(--green);font-size:.78rem;margin-top:12px}.actions{display:flex;gap:6px;flex-wrap:wrap}@media(max-width:900px){.library{grid-template-columns:1fr;height:auto}.pane{height:60vh}.reader.open{grid-template-columns:1fr}.reading{height:55vh}.sheet{height:45vh}}
@media print{body>*{display:none!important}.reader.open{display:block!important;position:static}.reading{display:none}.sheet{display:block!important;overflow:visible}.autosave,.actions,.rh{display:none!important}}
</style></head><body>
<header><div class="top"><div><div class="brand">Biblioteca de investigación</div><div class="sub">SCRAPEADORACADEMICO · buscar · revisar · leer · fichar</div></div><div class="actions"><a href="index.html">Dashboard</a><button onclick="exportAll()">Exportar fichas JSON</button></div></div><div class="tools"><input id="q" placeholder="Buscar título, autor, resumen, palabras clave o DOI..." autofocus><select id="year"><option value="">Todos los años</option></select><select id="state"><option value="">Todos los estados</option><option>Pendiente</option><option>Por leer</option><option>Leyendo</option><option>Leído</option><option>Fichado</option><option>Usado</option></select></div></header>
<main class="library"><section class="pane"><div class="ph"><b>Artículos scrapeados</b><span class="meta" id="count"></span></div><div class="list" id="articles"></div></section><section class="pane"><div class="ph"><b>Revisiones e informes</b><span class="meta">clic para pantalla completa</span></div><div class="list" id="reports"></div></section></main>
<div class="overlay" id="reportOverlay"><div class="ovh"><div><b id="rt"></b><div class="meta" id="rm"></div></div><button onclick="closeReport()">Cerrar</button></div><div class="ovbody" id="rb"></div></div>
<div class="reader" id="reader"><section class="reading"><div class="rh"><div><b id="readTitle"></b><div class="meta" id="readMeta"></div></div><div class="actions"><button onclick="externalOpen()">Abrir aparte</button><button onclick="closeReader()">Volver</button></div></div><div class="viewer" id="viewer"></div></section><section class="sheet" id="sheet"></section></div>
<script>
let A=[],R=[],F={},selected=null;const KEY='scrapeador_fichas_v2',$=x=>document.getElementById(x);function norm(v){return(v||'').toString().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}function esc(v){return(v||'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function attr(v){return esc(v).replace(/"/g,'&quot;')}function id(a){return a.record_id||a.doi||norm(a.title)}
async function init(){A=await fetch('library_articles.json',{cache:'no-store'}).then(x=>x.json());R=await fetch('report_history.json',{cache:'no-store'}).then(x=>x.json());try{F=JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){F={}};[...new Set(A.map(x=>x.year).filter(Boolean))].sort().reverse().forEach(y=>$('year').insertAdjacentHTML('beforeend',`<option>${esc(y)}</option>`));renderReports();filter()}
function state(a){return(F[id(a)]||{}).estado||'Pendiente'}function filter(){let q=norm($('q').value),y=$('year').value,st=$('state').value,x=A.filter(a=>(!q||norm([a.title,a.authors,a.abstract,a.keywords,a.doi,a.origin,a.source].join(' ')).includes(q))&&(!y||a.year===y)&&(!st||state(a)===st));$('count').textContent=x.length.toLocaleString()+' resultados';$('articles').innerHTML='';x.slice(0,700).forEach(a=>{let d=document.createElement('div');d.className='art';d.innerHTML=`<div class="title">${esc(a.title)}</div><div class="meta">${esc(a.authors)} · ${esc(a.year)} · ${esc(a.origin||a.source)}</div><span class="pill">${esc(state(a))}</span>${a.pdf_url?'<span class="pill">PDF</span>':''}`;d.onclick=()=>openReader(a);$('articles').appendChild(d)})}
function renderReports(){$('reports').innerHTML='';R.slice().reverse().forEach(r=>{let d=document.createElement('div');d.className='report';d.innerHTML=`<div class="report-date">${esc(r.date.split('-').reverse().join('/'))}</div><div class="title">Informe de actualización bibliográfica</div><div class="meta">${r.new} incorporaciones · base acumulada ${r.base}</div><div class="meta">${esc(r.sources)}</div>`;d.onclick=()=>openReport(r);$('reports').appendChild(d)})}
function openReport(r){let items=A.filter(a=>(a.first_seen_date||'').startsWith(r.date));$('rt').textContent='Informe · '+r.date.split('-').reverse().join('/');$('rm').textContent=`${r.new} incorporaciones · base ${r.base} · ${r.sources}`;$('rb').innerHTML=`<p class="meta">Se muestran ${items.length} registros identificados en la base para esta corrida.</p>`+items.map((a,i)=>`<div class="report-paper"><div class="title">${i+1}. ${esc(a.title)}</div><div class="meta">${esc(a.authors)} · ${esc(a.year)} · ${esc(a.origin||a.source)}</div>${a.doi?`<div class="meta">DOI: ${esc(a.doi)}</div>`:''}<button class="primary" onclick='readById(${JSON.stringify(id(a))})'>Leer y fichar</button></div>`).join('');$('reportOverlay').classList.add('open')}
function closeReport(){$('reportOverlay').classList.remove('open')}function readById(i){let a=A.find(x=>id(x)===i);if(a){closeReport();openReader(a)}}
function apaAuto(a){let au=(a.authors||'').split(';').map(x=>x.trim()).filter(Boolean);let author=au.length?au.join(', '):'Autor/a';return `${author} (${a.year||'s. f.'}). ${a.title}. ${a.origin||a.source||''}${a.doi?'. https://doi.org/'+a.doi:''}`}
function openReader(a){selected=a;let f=F[id(a)]||{};$('readTitle').textContent=a.title;$('readMeta').textContent=`${a.authors||''} · ${a.year||''}`;let src=a.pdf_url||a.url;$('viewer').innerHTML=src?`<iframe src="${attr(src)}"></iframe>`:`<div class="fallback"><h2>${esc(a.title)}</h2><p>${esc(a.abstract||'No hay PDF ni resumen disponible.')}</p></div>`;let val=(k,d='')=>f[k]!==undefined?f[k]:d;$('sheet').innerHTML=`<h2>Ficha de lectura</h2><div class="g2">${inp('titulo','Título',val('titulo',a.title))}${inp('anio','Año',val('anio',a.year))}</div>${inp('autores','Autores',val('autores',a.authors))}${inp('apa','Cita / referencia APA preliminar (editable)',val('apa',apaAuto(a)))}<div class="g2">${inp('doi','DOI',val('doi',a.doi))}${inp('fuente','Fuente / revista',val('fuente',a.origin||a.source))}</div><div class="g2">${sel('estado','Estado',['Pendiente','Por leer','Leyendo','Leído','Fichado','Usado'],val('estado','Leyendo'))}${sel('relevancia','Relevancia',['','Central','Alta','Media','Contextual','Descartar'],val('relevancia'))}</div>${inp('tipo_uso','Tipo de uso',val('tipo_uso'),'antecedente, marco conceptual, metodología, evidencia, discusión')}${ta('problema','Problema / pregunta del texto',val('problema'))}${ta('objetivo','Objetivo',val('objetivo'))}${ta('marco','Marco conceptual / conceptos',val('marco'))}${ta('metodo','Metodología / corpus',val('metodo'))}${ta('hallazgos','Hallazgos principales',val('hallazgos'))}${ta('citas','Citas textuales + número de página',val('citas'))}${ta('aporte','Aporte para mi investigación',val('aporte'))}${ta('discusion','Discusión propia / desacuerdos',val('discusion'))}${ta('relaciones','Relaciones con otros textos / autores',val('relaciones'))}${inp('proyecto','Dónde podría usarlo / proyecto',val('proyecto'))}${inp('tags','Etiquetas propias',val('tags'),'regulación, afectos, dirección escolar...')}${ta('notas','Notas libres',val('notas'))}<div class="actions"><button onclick="window.print()">Guardar ficha como PDF</button></div><div class="autosave" id="autosave">✓ Guardado automático activo</div>`;$('sheet').querySelectorAll('input,textarea,select').forEach(e=>{e.addEventListener('input',autosave);e.addEventListener('change',autosave)});autosave();$('reader').classList.add('open')}
function inp(k,l,v,p=''){return`<div class="form"><label>${l}</label><input data-k="${k}" value="${attr(v||'')}" placeholder="${attr(p)}"></div>`}function ta(k,l,v){return`<div class="form"><label>${l}</label><textarea data-k="${k}">${esc(v||'')}</textarea></div>`}function sel(k,l,opts,v){return`<div class="form"><label>${l}</label><select data-k="${k}">${opts.map(o=>`<option${o===v?' selected':''}>${esc(o)}</option>`).join('')}</select></div>`}
let timer;function autosave(){if(!selected)return;let f={...(F[id(selected)]||{})};$('sheet').querySelectorAll('[data-k]').forEach(e=>f[e.dataset.k]=e.value);f.updated_at=new Date().toISOString();F[id(selected)]=f;localStorage.setItem(KEY,JSON.stringify(F));let x=$('autosave');if(x){x.textContent='Guardando…';clearTimeout(timer);timer=setTimeout(()=>x.textContent='✓ Guardado automáticamente',350)}filter()}
function closeReader(){autosave();$('reader').classList.remove('open');selected=null}function externalOpen(){if(selected&&(selected.pdf_url||selected.url))window.open(selected.pdf_url||selected.url,'_blank')}
function exportAll(){let blob=new Blob([JSON.stringify(F,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='fichas_lectura.json';a.click();URL.revokeObjectURL(u)}$('q').oninput=filter;$('year').onchange=filter;$('state').onchange=filter;init();
</script></body></html>'''

def main():
    a=records(); (DOCS/'library_articles.json').write_text(json.dumps(a,ensure_ascii=False),encoding='utf-8'); (DOCS/'report_history.json').write_text(json.dumps(REPORTS,ensure_ascii=False,indent=2),encoding='utf-8'); (DOCS/'biblioteca.html').write_text(HTML,encoding='utf-8'); print(f'Biblioteca generada: {len(a)} artículos, {len(REPORTS)} informes')
if __name__=='__main__': main()
